{% set name = "CoTeDe" %}
{% set version = "0.23.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0]|lower }}/{{ name|lower }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: c3f562916e2e75b4768aa39a1af1391f3ccbe0906ecb213b93c364d2e0bb7a0b

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - numpy >=1.11.1
    - oceansdb >=0.8.11
    - scipy >=0.18.0

test:
  imports:
    - cotede
    - cotede.anomaly_detection
    - cotede.fuzzy
    - cotede.humanqc
    - cotede.qctests
    - cotede.utils

about:
  home: http://cotede.castelao.net
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Quality Control of Oceanographic Data
  doc_url: https://cotede.readthedocs.io/en/latest/?badge=latest
  dev_url: https://github.com/castelao/CoTeDe

extra:
  recipe-maintainers:
    - castelao
